[package]
name = "smol_base"
version = "0.1.0"
edition = "2021"

[dependencies]
# async
smol = "2.0.2"
event-listener = "5.3.1"
# errors
simple_error = { git = "https://github.com/brandonros/simple_error.git" }

[dev-dependencies]
env_logger = "0.11.5"
log = "0.4.22"
